<?php
 namespace app\admin\common;
 use app\admin\model\System;
 use think\Controller;
 use think\Request;
 use think\Session;

 class Base extends Controller{
  protected function _initialize(){
    parent::_initialize(); // TODO: Change the autogenerated stub
    //在公共控制器的初始化方法中，创建一个常量来判断用户是否登录，或已登录
    define('USER_ID', Session::get('user_id'));
    //获取网站配置信息

    $config=$this->getSystem();
    //获取当前请求对象
    $request = Request::instance();
    //查询一下当前网站开关状态
    $this->getStatus($request, $config);
  }
  //判断用户是否登录
   protected function isLogin(){
    //如果登录常量为NULL，表示没有登录
     if(is_null(USER_ID)){
      $this->error('未登录，无权访问~~','login/index');
     }
   }
   //如果用户已经登录，将不允许再次登录
   protected function alreadyLogin(){
    //如果登录常量为NULL，表示没有登录
     if(!is_null(USER_ID)){
      $this->error('请不要重复登录~~','index/index');
     }
   }

   //用来获取当前配置表System中的全部信息
   public function getSystem(){
     return System::get(1);
   }
   /**
    * 判断当前网站前台是关闭还是开启状态
    * @param $request 当前请求对像
    * @param $config  所有的配置信息
    */
   public function getStatus($request, $config){
     //判断当前模块是不是admin
     if($request->module()!=='admin'){
      //根据当前配置表中的is_close值来进行判断，如果为1开启，2则关闭，1为默认值
       if($config->is_close==2){
        $this->error('网站已关闭');
        exit();
       }
     }
   }

 }
